engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths: []
