# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsingjob',
            old_name='status_url',
            new_name='url',
        ),
    ]
