# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20160811_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulationfile',
            name='file',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
