# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_regulationfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulationfile',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
