# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_proposalpipelinejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinejob',
            name='destination',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='proposalpipelinejob',
            name='destination',
            field=models.URLField(max_length=2000),
        ),
    ]
