# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20160921_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulationfile',
            name='id',
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='notification_email',
            field=models.EmailField(blank='True', max_length=254),
        ),
        migrations.AlterField(
            model_name='pipelinejob',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('complete_with_errors', 'complete_with_errors'), ('failed', 'failed'), ('in_progress', 'in_progress'), ('received', 'received')], default='received', max_length=32),
        ),
        migrations.AlterField(
            model_name='proposalpipelinejob',
            name='file_hexhash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='proposalpipelinejob',
            name='notification_email',
            field=models.EmailField(blank='True', max_length=254),
        ),
        migrations.AlterField(
            model_name='proposalpipelinejob',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('complete_with_errors', 'complete_with_errors'), ('failed', 'failed'), ('in_progress', 'in_progress'), ('received', 'received')], default='received', max_length=32),
        ),
        migrations.AlterField(
            model_name='regulationfile',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='regulationfile',
            name='hexhash',
            field=models.CharField(default=None, max_length=64, primary_key=True, serialize=False),
        ),
    ]
