# Generated by Django 2.2.11 on 2020-04-11 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='depender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depends_on', to='index.DependencyNode'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_of', to='index.DependencyNode'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='label',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='index.DependencyNode'),
        ),
    ]
