# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFRVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('effective', models.DateField(blank=True, null=True)),
                ('fr_volume', models.IntegerField()),
                ('fr_page', models.IntegerField()),
                ('cfr_title', models.IntegerField()),
                ('cfr_part', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.BinaryField()),
                ('collection', models.CharField(choices=[('notice', 'notice'), ('gpo_cfr', 'gpo_cfr')], max_length=32)),
                ('label', models.CharField(max_length=128)),
                ('previous_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='index.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.BinaryField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='index.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.BinaryField()),
                ('collection', models.CharField(choices=[('notice', 'notice'), ('annual', 'annual')], max_length=32)),
                ('file_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sourcefile',
            unique_together=set([('collection', 'file_name')]),
        ),
        migrations.AlterIndexTogether(
            name='sourcefile',
            index_together=set([('collection', 'file_name')]),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='index.SourceFile'),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='index.CFRVersion'),
        ),
        migrations.AddField(
            model_name='diff',
            name='left_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='index.Document'),
        ),
        migrations.AddField(
            model_name='diff',
            name='right_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='index.Document'),
        ),
        migrations.AddField(
            model_name='cfrversion',
            name='delaying_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='index.SourceFile'),
        ),
        migrations.AddField(
            model_name='cfrversion',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='index.SourceFile'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([('collection', 'label', 'version')]),
        ),
        migrations.AlterIndexTogether(
            name='document',
            index_together=set([('collection', 'label', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='cfrversion',
            unique_together=set([('identifier', 'cfr_title', 'cfr_part')]),
        ),
        migrations.AlterIndexTogether(
            name='cfrversion',
            index_together=set([('identifier', 'cfr_title', 'cfr_part')]),
        ),
    ]
